### ISSUE TITLE
当我进行pod install的时候出现错误

### ISSUE THREAD

**Issue by tangzijun** [aliyun/alibabacloud-push-reactnative-plugin#16]
Cause: Unable to find a specification for `AlicloudPush` depended upon by `aliyun-react-native-push`

![image](https://github.com/aliyun/alibabacloud-push-reactnative-plugin/assets/11813048/9e93f89b-b7de-4eb3-b3a8-0217b8360c6f)

**Comment by vfasky** [comment]
找到 `ios/Podfile` 文件，在顶部插入 

```
source 'https://github.com/aliyun/aliyun-specs.git'
```
