### ISSUE TITLE
如何接入厂商通道？

### ISSUE THREAD

**Issue by qilovehua** [aliyun/alibabacloud-push-reactnative-plugin#30]
app打开的时候，能收到推送。
app没有打开的时候，收不到；发现需要单独接入厂商通道才行。
按照[接入文档](https://help.aliyun.com/document_detail/434684.html?spm=a2c4g.434677.0.0.26904132lANeRg#topic-1996993)操作的，使用方案一“自定义Activity继承自AndroidPopupActivity”，编译的时候提示“Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath: class com.myapp.push.PopupPushActivity, unresolved supertypes: AndroidPopupActivity”。
看了源码没有AndroidPopupActivity，又在android/app/build.gradle的dependencies里加了implementation 'com.aliyun.ams:alicloud-android-push:3.8.7'，还是这么提示错误。

有解决厂商通道的推送吗？这个地方要怎么改？谢谢

**Comment by qilovehua** [comment]
`import com.alibaba.sdk.android.push.AndroidPopupActivity;`

这句报错

**Comment by qilovehua** [comment]
<img width="943" alt="image" src="https://github.com/user-attachments/assets/09a1fb31-1dda-4de6-81ba-a1c0930f7885">
从flutter那里看到的，能显示离线推送了

**Comment by qilovehua** [comment]
> `import com.alibaba.sdk.android.push.AndroidPopupActivity;`
> 
> 这句报错

这句应该怎么改？要处理语音播报，不能直接用MainActivity了

**Comment by qilovehua** [comment]
implementation 'com.aliyun.ams:alicloud-android-utdid:2.6.0'
加已经这个 就不报错了

**Comment by ly678910** [comment]
implementation "com.aliyun.ams:alicloud-android-third-push:3.8.7" 在app/build.gradle加这个,才不会报错
