### ISSUE TITLE
android通知栏不显示，监听有内容

### ISSUE THREAD

**Issue by hzlgit** [aliyun/alibabacloud-push-reactnative-plugin#8]
android通知栏不显示，应用在前台后台都没有，监听有内容，

**Comment by hzlgit** [comment]
android8以上通道问题，已解决

**Comment by lydat** [comment]
> android8以上通道问题，已解决

我也不显示,方便说下是什么问题吗

**Comment by wangyun137** [comment]
8.0以上需要调用AliyunPush.createAndroidChannel方法创建通知的channel
